### PR TITLE
fixes for cordova-lib 9.0.0+

### PR DESCRIPTION
**Pull request by mvakulich**
support for latest cordova lib
support for latest android project structure

### CODE REVIEW

**Comment by DzmitrySidarau** [comment]
Hello.
I have an error when installing this fork for both android and IOS

[17:00:09][Step 6/11] Installing "cordova-plugin-app-preferences" for android
[17:00:09][Step 6/11] Failed to install 'cordova-plugin-app-preferences': Error: Cannot find module 'cordova-lib'
[17:00:09][Step 6/11]     at Function.Module._resolveFilename (module.js:470:15)
[17:00:09][Step 6/11]     at Function.Module._load (module.js:418:25)
[17:00:09][Step 6/11]     at Module.require (module.js:498:17)
[17:00:09][Step 6/11]     at require (internal/module.js:20:19)
[17:00:09][Step 6/11]     at module.exports (/Users/teamdev/TeamCityBuildAgent/work/8b83ab22f97f06b5/Selfcare/plugins/cordova-plugin-app-preferences/bin/lib/android.js:11:17)
[17:00:09][Step 6/11]     at module.exports (/Users/teamdev/TeamCityBuildAgent/work/8b83ab22f97f06b5/Selfcare/plugins/cordova-plugin-app-preferences/bin/after_plugin_install.js:8:37)
[17:00:09][Step 6/11]     at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:181:32)
[17:00:09][Step 6/11]     at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:157:16)
[17:00:09][Step 6/11]     at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:125:20
[17:00:09][Step 6/11]     at process._tickCallback (internal/process/next_tick.js:103:7)
[17:00:09][Step 6/11] Cannot find module 'cordova-lib'

**Comment by NemSavic** [comment]
@mvakulich @DzmitrySidarau 
Sorry for the slow response. I actually created this fork just to create a PR for the Cordova 9.0.0 update to the original repository. You can find that PR here https://github.com/apla/me.apla.cordova.app-preferences/pull/148, however it looks like the project may have been abandoned.

My fix can be found in the following branch: https://github.com/NemSavic/me.apla.cordova.app-preferences/tree/cordova-9.0.0. You're welcome to try it out. I was only ever able to test it on iOS.

**Comment by NemSavic** [comment]
@mvakulich I merged your Android structure changes with the Cordova 9.0.0 update I added 😄 

Thanks for your help!

**Comment by arnaud-zad** [comment]
I still have the same issue. I added the library like this in my package.json : 
`
"cordova-plugin-app-preferences": "github:NemSavic/me.apla.cordova.app-preferences"
`

Failed to install 'cordova-plugin-app-preferences': Error: Cannot find module 'cordova-lib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    ....

**Comment by NemSavic** [comment]
@arnaud-zad I believe I just resolve the issue, can you try again?

**Comment by arnaud-zad** [comment]
@NemSavic Yes it fixed the issue. But now another one is appearing : 

Installing "cordova-plugin-app-preferences" for android
Failed to install 'cordova-plugin-app-preferences': Error: Cannot find module 'xcode'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

**Comment by NemSavic** [comment]
@arnaud-zad hmm I can't seem to recreate that issue, maybe it's because I don't have a real android project, but to me it looks like we just need to add `xcode` as a dependency.

I just made a change where I added `xcode` as well ass `elementtree`, `plist`, and `q` to the dependencies. Can you try that out?

**Comment by arnaud-zad** [comment]
@NemSavic Yes it worked ! Thank you.

**Comment by Arpapiemonte** [comment]
Sorry, I have the same problem trying to install cordova-plugin-app-preferences in ionic with cordova 9.
I want to try your fixed code, but I don't know which command use.
Normally I pass these command:
`ionic cordova plugin add cordova-plugin-app-preferences`
`npm install @ionic-native/app-preferences`
And the I import the plugin in this way in my ts file:
`import { AppPreferences } from '@ionic-native/app-preferences/ngx';`

Can you help me and say which command I have to use to install your fixed plugin version?
I will test it both in Android then in iOS.
Thanks

**Comment by NemSavic** [comment]
@Arpapiemonte I could be wrong but I think you can install the fork with
`ionic cordova plugin add https://github.com/NemSavic/me.apla.cordova.app-preferences`

**Comment by Arpapiemonte** [comment]
@NemSavic: thank you very mach!!!!
It works!!!!!
Great job!
After: 
`ionic cordova plugin add https://github.com/NemSavic/me.apla.cordova.app-preferences`
as usual, it's necessary to give:
`npm install @ionic-native/app-preferences`
and import in the ts file with:
`import { AppPreferences } from '@ionic-native/app-preferences/ngx';`
Thta's all.
Thanks

**Pull request merged**
